# Generated by Django 5.2 on 2025-04-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('release_year', models.IntegerField()),
                ('genre', models.CharField(max_length=20)),
                ('cast', models.TextField()),
                ('story', models.TextField()),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('your_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('watchlist', models.BooleanField(default=False)),
                ('poster', models.ImageField(upload_to='')),
                ('landscape', models.ImageField(upload_to='')),
            ],
        ),
    ]
