# Generated by Django 5.2 on 2025-04-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='your_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
